server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lower-case-service-id: true
              enabled: true
          routes:
            - id: employee
              uri: lb://employee
              predicates:
                - Path=/api/v1/employees/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 500
                    redis-rate-limiter.burstCapacity: 1000
                    redis-rate-limiter.requestedTokens: 1
                - KeyAuthFilter
            - id: userservice
              uri: http://localhost:9005
              predicates:
                - Path=/api/v1/users/**
              filters:
                - name: JwtHeaderFilter
            - id: userservice-pulic
              uri: http://localhost:9005
              predicates:
                - Path=/api/v1/public/**

  data:
    redis:
      port: 6379
      host: localhost
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/master

eureka:
  client:
    service-url:
      defaultZone: http://discoveryserver.default.svc.cluster.local:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG