server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lower-case-service-id: true
              enabled: true
          routes:
            - id: employee
              uri: lb://employee
              predicates:
                - Path=/api/v1/employees/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 500
                    redis-rate-limiter.burstCapacity: 1000
                    redis-rate-limiter.requestedTokens: 1
                - KeyAuthFilter
            - id: client
              uri: lb://client
              predicates:
                - Path=/api/v1/books/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 500
                    redis-rate-limiter.burstCapacity: 1000
                    redis-rate-limiter.requestedTokens: 1
                - KeyAuthFilter
  data:
    redis:
      port: 6379
      host: localhost

eureka:
  instance:
    hostname: discoveryserver
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://discoveryserver:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG